---
- hosts: 172.31.0.218 
  become: yes
  tasks: 
  - name: i want to execute direct linux command 
    command: hostname -f
    register: myresult

  - name: i want to display ny first result 
    debug:
       msg: "{{myresult}}"
