---
- hosts: 172.31.0.218 
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: i want to install java 
    apt:
      name: apache2 
      state: present 

  - name: i want to create a folder 
    file:  
       path: /home/maha/myfolder
       state: directory

  - name: copy a file into node side
    copy:
      src: mytextfile
      dest: /home/maha/myfolder/mytextfile

  - name: download any internet file 
    get_url:
      url: https://updates.jenkins.io/download/war/2.507/jenkins.war
      dest: /home/maha/myfolder/jenkins.war
      force_basic_auth: yes

  - name: i want to copy index file into node side 
    template:
        src: myindex.j2
        dest: /var/www/html/index.html
    notify: startwebserver

  handlers: 
  - name: startwebserver
    service:
       name: apache2
       state: present


   
