---
- hosts: mywebserers
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to install apache2 webserver ( apt-get install apache2 )
    apt: 
      name: "{{myubuntuwebpack}}"
      state: present
    when: ansible_os_family=="Debian" 

  - name: i want to start apache2 webserver ( service apache2 start)
    service:
       name: "{{myubuntuwebpack}}"
       state: started
    when: ansible_os_family=="Debian"


  - name: i want to install httpd webserver (yum install httpd)
    dnf:
      name: "{{myredhatwebpack}}"
      state: present
    when: ansible_os_family=="RedHat"


  - name: i want to start httpd webserver ( service httpd start)
    service:
      name: "{{myredhatwebpack}}"
      state: started
    when: ansible_os_family=="RedHat"

# apt-get install apache2  for install webserver  Debian family 
# yum install httpd      for install webserver on RedHat  family 

    


